# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: safechat-mongodb
    ports:
      - "27017:27017" # Porta padrão do MongoDB
    volumes:
      - mongodb_data:/data/db # Persistir dados do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

volumes:
  mongodb_data: